print("madlibs")
x = input("escoge una profesion")
y = input("escoge un lugar con agua ")
z = input("escoge un elemento ")
a = input("escoge planeta")
b = input("escoge un ecosistema")

print("------------------------------------------")
print(f"seremos {x} que surcan el {y}")
print(f"el {z} se enciende y crea problemas")
print(f"en {a} planeta perdido")
print(f"su tierra de  {a} debe ser limpia ")
print(f"si bebes del {y} parece estar limpia ")
print(f"parece que estamos varados en {b}")
print("------------------------------------------")